"""Laporan penalti dan indeks berkas agar hasil mudah ditemukan."""
import json
from pathlib import Path
BASE=Path(__file__).parent;NET=BASE/'network_diy'
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def link(label,p):return f'[{label}]({p.resolve().as_posix()})'
def run():
    p=load(NET/'poi/penalty_report.json');v=load(NET/'validation_poi_report.json');old=load(NET/'validation_report.json');q=load(NET/'poi/geometry_review.json')
    baseline={(r['scenario'],r['start']):r for r in old['results']};deltas=[]
    for r in v['results']:
        b=baseline[(r['scenario'],r['start'])]
        if r['expected_s'] is not None and b['expected_s'] is not None:
            delta=r['expected_s']-b['expected_s'];assert delta>=-1e-6;deltas.append(delta)
    local=q['unresolved_with_known_vertices_in_model_region']
    counts=p['poi_objects']
    rows=['# Hasil penambahan penalti sekolah, pasar, dan mal','',f"Data OSM area jaringan DIY beserta penyangganya: **{counts['school']:,} objek sekolah**, **{counts['market']:,} pasar**, dan **{counts['mall']} mal**. Ini jumlah objek peta, bukan jumlah lembaga unik atau inventaris resmi yang dijamin lengkap.",'',f"Graf tetap {p['nodes']:,} node, {p['directed_edges']:,} ruas berarah, serta {p['goals']} titik tujuan jalan proksi untuk kandidat RS. Enam kandidat RS lainnya tetap memerlukan pemeriksaan sambungan.",'','## Parameter awal','', '| Faktor | Radius | Pagi | Siang | Sore | Malam |','|---|---:|---:|---:|---:|---:|','| Sekolah | 100 m | 20 | 15 | 5 | 0 |','| Pasar | 150 m | 30 | 20 | 15 | 5 |','| Mal | 200 m | 5 | 15 | 25 | 10 |','', 'Angka tabel adalah tambahan **detik per 100 meter jalan di dalam zona**. Zona dibuat dari titik atau batas area OSM. Skenario hari kerja: pagi 06–09, siang 09–15, sore 15–19, malam 19–06 WIB. Biaya dibekukan sepanjang perjalanan berdasarkan skenario keberangkatan.','', 'Total = waktu dasar + paparan sekolah/pasar/mal + penalti node lampu + penalti node perlintasan. Semua komponen dalam detik. Radius dan besar penalti adalah asumsi awal, bukan pengukuran kemacetan langsung.','', 'Zona sejenis digabung dengan union agar area tumpang tindih tidak dihitung berkali-kali. Efek antarjenis dijumlahkan; potensi tumpang tindih penyebab kemacetan masih perlu kalibrasi. Segmen berlabel bridge atau tunnel diberi paparan POI nol sebagai pendekatan pemisahan tingkat.','', '## Pemeriksaan yang selesai','', '- 20 tes otomatis lulus, termasuk tumpang tindih area, duplikasi fitur, satuan biaya, serta invariansi ketika ruas dipecah.',f"- {v['query_pairs']} kueri berpasangan pada empat skenario: biaya A* dan UCS cocok dengan NetworkX pada graf state belok yang dibuat secara terpisah.",'- Semua panjang paparan berada antara nol dan panjang ruas. Biaya empat skenario positif, terbatas, dan tidak lebih kecil daripada batas bawah heuristik.', '- Biaya skenario yang disimpan sama dengan biaya yang dihitung ulang mesin pencarian.',f"- Pada sampel yang terjangkau, {sum(d>1e-6 for d in deltas)} dari {len(deltas)} kueri memiliki biaya optimal lebih tinggi dibanding graf tanpa POI. Ini pemeriksaan dampak parameter, bukan validasi waktu lapangan.",'', '## Kualitas geometri dan batas hasil','',f"Ada {len(local)} objek bermasalah dengan koordinat yang diketahui berada di area model; objek tersebut tidak dipakai untuk penalti sampai geometrinya diperbaiki:",'']
    rows += [f"- {r['name'] or '(tanpa nama)'} ({r['osm_type']}/{r['osm_id']}): {r['reason']}." for r in local]
    rows += ['', '- Untuk Plaza Ambarrukmo, batas outer yang tertutup dipakai; anggota dengan peran nonstandar balcony diabaikan dan dicatat pada geometry_notes.','- Kelengkapan sekolah/pasar/mal bergantung pada tag OSM amenity=school, amenity=marketplace, shop=mall. Lokasi yang tidak memiliki tag tersebut belum tercakup.','- Status layanan IGD, akses fisik dari titik jalan ke RS, dan kemampuan klinis bukan hasil verifikasi tahap ini.','- Penalti lampu/palang masih per node OSM; pengelompokan node menjadi satu kejadian fisik dan kalibrasi perjalanan nyata belum selesai.','- Pengujian ini memvalidasi implementasi pencarian pada model. Belum membuktikan akurasi ETA ambulans di lapangan.','', '## Berkas utama','',link('Graf dengan penalti lokasi',NET/'graph_diy_poi.json'),'',link('Data geometri lokasi',NET/'poi/poi_features.geojson'),'',link('Hasil pemeriksaan pencarian',NET/'validation_poi_report.json'),'',link('Contoh rute pengujian',NET/'example_poi_route.json')]
    (BASE/'Hasil_Penalti_Lokasi_DIY.md').write_text('\n'.join(rows)+'\n',encoding='utf-8')
    table=[('Rancangan dan asumsi model',BASE/'Rancangan_Model_AI_DIY.md'),('50 kandidat RS hasil filter',BASE/'Daftar_RS_Umum_DIY_Tersaring.md'),('Laporan graf dasar (sebelum POI)',BASE/'Hasil_Jaringan_Jalan_DIY.md'),('Laporan terbaru: penalti lokasi',BASE/'Hasil_Penalti_Lokasi_DIY.md'),('Graf terbaru untuk pencarian',NET/'graph_diy_poi.json'),('Lokasi RS dan status sambungan',NET/'hospital_road_mapping.json'),('Geometri sekolah/pasar/mal',NET/'poi/poi_features.geojson'),('Radius, penalti dan statistik',NET/'poi/penalty_report.json'),('Pengujian A*/UCS terbaru',NET/'validation_poi_report.json'),('Contoh rute pengujian',NET/'example_poi_route.json'),('Peta jaringan jalan dan RS',BASE/'Peta_Jaringan_RS_DIY.png'),('Mesin pencarian dengan larangan belok',BASE/'route_network.py')]
    guide=['# Mulai dari sini: lokasi berkas proyek','',f"Folder proyek: `{BASE.parent}`",'', '**Dokumen, program, serta data hasil pengolahan berada di folder outputs.** Anda tidak perlu memindahkan berkasnya.','', '## Berkas yang paling sering dipakai','', '| Kegunaan | Berkas |','|---|---|']
    guide += [f'| {purpose} | {link(path.name,path)} |' for purpose,path in table]
    guide += ['', '## Data sumber dan berkas sementara','', r'- Peta sumber asli: `C:\Users\LENOVO\Downloads\java-260920.osm.pbf` (sekitar 897 MB). Berkas ini dibaca saja, tidak diedit.',f'- Folder `work` pada proyek berisi lingkungan Python `.venv` serta checkpoint proses ekstraksi. Simpan selama proyek dikerjakan agar tidak perlu mengulang pembacaan peta.', '- Folder outputs/data_offline berisi daftar kandidat RS serta catatan penyaringan.', '- Folder outputs/network_diy berisi graf, relasi jalan, pemetaan RS, dan hasil pengujian.', '- Folder outputs/network_diy/poi berisi sekolah, pasar, mal, zona pengaruh, parameter penalti, dan catatan kualitas geometri.', '- Folder outputs/data_osm/cache berisi batas DIY yang dipakai untuk menyaring wilayah.','', '## Cara memakai versi terbaru','', 'Untuk sekarang cukup buka laporan penalti terbaru di tabel. Anda belum perlu membaca berkas JSON yang besar.', '', 'Program route_network.py otomatis memakai graph_diy_poi.json jika tersedia. Untuk menjalankan rute diperlukan ID node jalan awal; lokasi kejadian berupa alamat/koordinat perlu dipetakan terlebih dahulu.', '', 'Dari PowerShell pada folder outputs, perintah pengecekan ulang:', '', '```powershell', '& "..\\work\\.venv\\Scripts\\python.exe" validate_network.py --poi', '```', '', '**Status:** biaya POI empat skenario sudah tersedia dan diuji secara komputasi. Estimasi waktu belum dikalibrasi terhadap perjalanan ambulans nyata.']
    (BASE/'LOKASI_BERKAS.md').write_text('\n'.join(guide)+'\n',encoding='utf-8')
    print('Ringkasan penalti dan petunjuk lokasi berkas tersimpan.')
if __name__=='__main__':run()
